version: '3.8'
services:

  #
  # A standalone deployment of the Curity Identity Server, with customized resources
  #
  curity-idsvr:
    image: curity.azurecr.io/curity/idsvr:latest
    hostname: idsvr
    ports:
     - 6749:6749
     - 8443:8443
    volumes:
     - ./config-backup.xml:/opt/idsvr/etc/init/config.xml
     - ./license.json:/opt/idsvr/etc/init/license/license.json
$CUSTOM_RESOURCES
    environment:
      ADMIN: 'true'
      PASSWORD: 'Password1'
      LOGGING_LEVEL: 'INFO'

  #
  # Also deploy a Docker based mail server, for sending login related emails
  # Then browse to http://localhost:8080 to see received emails, such as those for reset password
  #
  smtp-server:
    image: maildev/maildev
    hostname: smtpserver
    environment:
      MAILDEV_INCOMING_USER: 'noreply@example.com'
      MAILDEV_INCOMING_PASSWORD: 'Password1'
    ports:
      - 1080:1080
      - 1025:1025
